# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f2a31048451944d74450f9c332df6a575558b3a6f1cace25d66905276da2adc8e33c5c9bbc632de9aa40905fa4b37e540699dfd69f37fb3345775ac489f8aa57

test:
  secret_key_base: e15fd4523f601ca9cef92274a595c6c743812675cd311f2a10a8a8302ddf65e7f931925429f38a700c2422d0b7798d7ed422520573366bc7848e49f3d8aa19aa

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
